### ISSUE TITLE
CodeStream server is behind a firewall

### ISSUE THREAD

**Issue by duicym** [TeamCodeStream/codestream-server#103]
We’re having problems connecting to CodeStream. Hold tight, we’ll keep trying...
If your CodeStream server is behind a firewall, make sure you're connected to your VPN.

Error code: BCOM-1004

**Comment by duicym** [comment]
sign up and sign in is ok.
when I invite teammates calls this issue

**Comment by planteater** [comment]
@duicym - Are you based in China? I suspect that this is simply a Great Firewall issue. 

Can you try hitting the following URL and let me know if it returns "OK"?

https://api.codestream.com/no-auth/status
