### ISSUE TITLE
Impossible to repeat install instructions

### ISSUE THREAD

**Issue by momentics** [TeamCodeStream/codestream-server#186]
Hello Gents,
I spent too much time to folow README.md and tried to install server's packages. Tried <develop> and <master> branches, with different nodejs versions with no hope.
Early nodejs versions warns of lots of warnings or\and errors, the only that installs nodemonules is 16.13.2 (npm 8.1.2). Docker images for rabbitmq and monodb were installed as per instructions. However, start:api was unable to deploy collections taht it was unable to connect to the database at all.

Sequence:
1. git clone https://github.com/teamcodestream/codestream-server
2. cd codestream-server
3. source dev-env.sh
4. npm run install:all
5. (checked manually - works) npm run run:docker:csrabbitmq
6. (checked manually - works) npm run run:docker:csmongo

different shell

7. source dev-env.sh
8. npm run start:api

And it cannot deploy collections and indexes with the following errors:

> codestream-server@1.0.0 start:api
> cd api_server && npm run start

> api-server@13.0.3 start
> bin/ensure-indexes.js && bin/api_server.js --one_worker

> mongo connect error MongoServerSelectionError: Server at localhost:27017 **reports maximum wire version 5, but this version of the Node.js Driver requires at least 6** (MongoDB 3.6)
    at Timeout._onTimeout (/data/codestream/codestream-server/api_server/node_modules/mongodb/lib/sdam/topology.js:318:38)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) { 'localhost:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    logicalSessionTimeoutMinutes: undefined
  },
  code: undefined,
  [Symbol(errorLabels)]: Set(0) {}
}

And of course, I tried to replace to mongodb 3.6, but it cannot use Topology becasue of old-style of reconnect connections parameters in its connection string.
It deploys connections and indexes (!), however does not work later :(

What can be done? Please help.

_Gentoo X64. Docker version 20.10.17
node v16.13.2 npm 8.1.2_

**Comment by planteater** [comment]
My apologies @momentics but the on-prem version of CodeStream was retired last summer.
