### ISSUE TITLE
npm run install:all报错

### ISSUE THREAD

**Issue by Gavinzqk** [TeamCodeStream/codestream-server#49]
Failed at the codestream-server@1.0.0 install:all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

**Comment by jimmyjayp** [comment]
Can you please elaborate on what you are trying to do?  From the look of that error, it appears you're doing something that should happen after an npm install, but that was never completed.  It's hard to diagnose without more info.

The instructions for building are in the main readme for the repository. You have to follow the steps in sequence. Step 2 requires you source in dev-env.sh and step 3 will have you run `npm run install:all` which is what will ultimately install node_modules/ for all the services. Note that there is no node_modules off the repo root.  It's a mono-repo that includes 5 different services.

**Comment by jimmyjayp** [comment]
No movement in 6 weeks. Closing the issue.
