### ISSUE TITLE
Issues with mail server

### ISSUE THREAD

**Issue by orellabac** [TeamCodeStream/codestream-server#68]
Hi Recently I tried to reset a password. However when I tried never got the reset email.

Looking at the logs it seems I got this error message:

2021-05-15 14:22:34.999Z W1 ERROR: Error making SMTP request: {"library":"SSL routines","function":"ssl3_get_record","reason":"wrong version number","code":"ESOCKET","command":"CONN"}

What am I missing?

**Comment by jimmyjayp** [comment]
Sorry, but this is not enough information to help you troubleshoot. Please upload the entire client log as an attachment. Also, are you running your own codestream-server or pointing your IDE to CoudeStream Cloud?

**Comment by jimmyjayp** [comment]
I also see in the error that you're using SSL version 3.0 in the client. This is a __really__ old version of SSL, has vulnerabilities and isn't supported by most services on the internet.  Assuming you're running your own codestream server and are using NodeMailer, can you please send me the NodeMailer section of your configuration file.

**Comment by orellabac** [comment]
mmm I am not sure what you need.  "email": {
                "emailTo": null,
                "notificationInterval": 300000,
                "replyToDomain": "mydomain.com",
                "senderEmail": "email@mydomain.com",
                "supportEmail": "email@mydomain.com",
                "suppressEmails": false
        },
        "emailDeliveryService": {
                "NodeMailer": {
                        "host": "smtp.office365.com",
                        "password": "mysecretpassword",
                        "port": 587,
                        "secure": true,
                        "service": "office365",
                        "username": "email@mydomain.com"
                }
        },

**Comment by orellabac** [comment]
Also I can update the SSL I just do not know how. Let me check if I can find it out

**Comment by jimmyjayp** [comment]
Ok, that will help. We don't use office365 here so I'm going to have to setup a test environment to dig deeper into this. Will get back to you as soon as I can.

**Comment by erickyb** [comment]
quisiera participar

**Comment by bcanzanella** [comment]
CodeStream no longer supports an on-prem solution. Sorry about that!
