### ISSUE TITLE
missing "start" script in package.json of inbound_email & outbound_email

### ISSUE THREAD

**Issue by jeange1003** [TeamCodeStream/codestream-server#86]
I'm following the installation guide in README.
The last two steps are 
```
source dev-env.sh
npm run start:mailin
```
and
```
source dev-env.sh
npm run start:mailout
```
Which actually run scripts in inbound_email and outbound_email
```
"start:mailin": "cd inbound_email && npm run start",
"start:mailout": "cd outbound_email && npm run start",
```
But _start_ scripts are missing in both packages

**Comment by planteater** [comment]
@jeange1003 - I'm afraid that CodeStream's on-prem offering is no longer available.
